name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: eclipse-temurin:21.0.4_7-jdk
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Build
        run: echo "Building..."
  test-component:
    needs: build
    runs-on: ubuntu-latest
    container: eclipse-temurin:21.0.4_7-jdk
    steps:
      - name: Test
        run: echo "Testing..."
  deploy-staging:
    needs: test-component
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: deploy
        run: echo "Deploying..."
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
        run: echo "Deploying..."
